services:
  url-checker:
    build: .
    container_name: url-checker
    ports:
      - "8001:8000"
    restart: unless-stopped
    # Για ανάπτυξη: ζωντανή φόρτωση αλλαγών
    # volumes:
    #   - ./src:/app
    # command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload